# Generated by Django 5.2.6 on 2025-09-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minimark', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Product',
        ),
    ]
